# Generated by Django 3.1.7 on 2021-04-30 03:15
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_usertype_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id',
                 models.AutoField(primary_key=True,
                                  null=False,
                                  editable=False,
                                  unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_type',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='api.user_types')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=50))
            ],
        ),
    ]
