# Generated by Django 3.1.7 on 2021-05-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_infomation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates_Class',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FileStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttending',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('isAttending', models.BooleanField()),
                ('dateClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dates_class')),
            ],
        ),
        migrations.RemoveField(
            model_name='student_attendances',
            name='date_class',
        ),
        migrations.RemoveField(
            model_name='student_attendances',
            name='student',
        ),
        migrations.AlterField(
            model_name='classes',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subjects'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='dates_of_class',
        ),
        migrations.DeleteModel(
            name='student_attendances',
        ),
        migrations.AddField(
            model_name='studentattending',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AddField(
            model_name='dates_class',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classes'),
        ),
    ]
